apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: gitops-operator
  name: gitops-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - interval: 10s
    port: default-metrics
    scheme: http
  selector:
    matchLabels:
      control-plane: gitops-operator
