apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: gitops-operator
  name: gitops-operator-controller-manager-metrics-service
spec:
  ports:
  - name: default-metrics
    port: 8080
    targetPort: 8080
  selector:
    control-plane: gitops-operator
status:
  loadBalancer: {}
